version: '3'

# For local development 
# 3 back ends services = 3 ports: 8080, 8081, 8082 
services:
  auth-component:
    build:
      context: Back-end/auth-component
      dockerfile: Dockerfile
    volumes:
      - ./Back-end/auth-component/:/usr/src/app
    ports:
      - "8080:80"

  get-videos-meta-component:
    build:
      context: Back-end/get-videos-meta-component
      dockerfile: Dockerfile
    volumes:
      - ./Back-end/get-videos-meta-component/:/usr/src/app
    ports:
      - "8081:80"

  analyze-camera-event-component:
    build:
      context: Back-end/analyze-camera-event-component
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/custom-service-account.json 
    volumes:
      - ./Back-end/analyze-camera-event-component/:/usr/src/app
      - ~/.config/gcloud:/root/.config/gcloud # this component needs service account to upload to GCS bucket.
    ports:
      - "8082:80"

  # TODO: add front-end here
